fix: report pipeline status

diff --git a/.github/actions/deployment-reporting/action.yaml b/.github/actions/deployment-reporting/action.yaml
--- a/.github/actions/deployment-reporting/action.yaml
+++ b/.github/actions/deployment-reporting/action.yaml
@@ -18,7 +18,7 @@ runs:
       with:
         name: manifests.yaml
         path: manifests.yaml
-
+    
     - name: Notify deployment end
       uses: bobheadxi/deployments@v1
       if: ${{ env.DEPLOYMENT_OK == 'true' }}
@@ -34,3 +34,12 @@ runs:
       uses: socialgouv/kontinuous/.github/actions/debug-manifests@v1.96.10
       with:
         token: ${{ inputs.token }}
+
+    - name: Report pipeline status
+      shell: bash
+      run: |
+        if [ "$DEPLOYMENT_OK" != "true" ]; then
+          echo "Pipeline failed"
+          echo 'see "Kontinupus Pipeline" step to inspect full logs'
+          exit 1
+        fi
